// Auto-generated by scripts/build-from-collections.ts — DO NOT EDIT MANUALLY
// Source of truth: scripts/token-collections/*.json
// Regenerate with: npm run build:tokens:local  (from packages/tokens)

export const breakpoints = {
  xs: 320,
  sm: 480,
  md: 768,
  lg: 1024,
  xl: 1280,
  '2xl': 1536,
} as const;

export type Breakpoint = keyof typeof breakpoints;
