// Auto-generated by scripts/build-from-collections.ts — DO NOT EDIT MANUALLY
// Source of truth: scripts/token-collections/*.json
// Regenerate with: npm run build:tokens:local  (from packages/tokens)

export const semanticColors = {
  background: {
    primary: {
      default: {
        light: '#2563EB',
        dark: '#3B82F6',
      },
      hover: {
        light: '#1D4ED8',
        dark: '#60A5FA',
      },
      active: {
        light: '#1E40AF',
        dark: '#93C5FD',
      },
      disabled: {
        light: '#E5E5E5',
        dark: '#404040',
      },
    },
    secondary: {
      default: {
        light: '#F5F5F5',
        dark: '#262626',
      },
      hover: {
        light: '#E5E5E5',
        dark: '#404040',
      },
      active: {
        light: '#D4D4D4',
        dark: '#525252',
      },
      disabled: {
        light: '#F5F5F5',
        dark: '#262626',
      },
    },
    error: {
      default: {
        light: '#DC2626',
        dark: '#EF4444',
      },
      hover: {
        light: '#B91C1C',
        dark: '#F87171',
      },
    },
    warning: {
      default: {
        light: '#EAB308',
        dark: '#FACC15',
      },
      hover: {
        light: '#CA8A04',
        dark: '#FDE047',
      },
    },
    success: {
      default: {
        light: '#16A34A',
        dark: '#22C55E',
      },
      hover: {
        light: '#15803D',
        dark: '#4ADE80',
      },
    },
    info: {
      default: {
        light: '#3B82F6',
        dark: '#60A5FA',
      },
      hover: {
        light: '#2563EB',
        dark: '#93C5FD',
      },
    },
    neutral: {
      default: {
        light: '#F5F5F5',
        dark: '#262626',
      },
      hover: {
        light: '#E5E5E5',
        dark: '#404040',
      },
      subtle: {
        light: '#FFFFFF',
        dark: '#171717',
      },
    },
  },
  surface: {
    default: {
      light: '#FFFFFF',
      dark: '#171717',
    },
    raised: {
      light: '#FFFFFF',
      dark: '#262626',
    },
    overlay: {
      light: '#FFFFFF',
      dark: '#262626',
    },
    sunken: {
      light: '#FFFFFF',
      dark: '#0A0A0A',
    },
  },
  text: {
    primary: {
      default: {
        light: '#171717',
        dark: '#FFFFFF',
      },
      disabled: {
        light: '#A3A3A3',
        dark: '#525252',
      },
    },
    secondary: {
      default: {
        light: '#525252',
        dark: '#A3A3A3',
      },
      disabled: {
        light: '#D4D4D4',
        dark: '#404040',
      },
    },
    error: {
      default: {
        light: '#DC2626',
        dark: '#F87171',
      },
    },
    warning: {
      default: {
        light: '#A16207',
        dark: '#FACC15',
      },
    },
    success: {
      default: {
        light: '#15803D',
        dark: '#4ADE80',
      },
    },
    info: {
      default: {
        light: '#2563EB',
        dark: '#60A5FA',
      },
    },
    'on-primary': {
      default: {
        light: '#FFFFFF',
        dark: '#FFFFFF',
      },
    },
    'on-secondary': {
      default: {
        light: '#171717',
        dark: '#FFFFFF',
      },
    },
    placeholder: {
      default: {
        light: '#A3A3A3',
        dark: '#737373',
      },
    },
  },
  border: {
    default: {
      default: {
        light: '#E5E5E5',
        dark: '#404040',
      },
      hover: {
        light: '#A3A3A3',
        dark: '#737373',
      },
      focus: {
        light: '#3B82F6',
        dark: '#60A5FA',
      },
    },
    error: {
      default: {
        light: '#EF4444',
        dark: '#F87171',
      },
    },
    success: {
      default: {
        light: '#22C55E',
        dark: '#4ADE80',
      },
    },
    primary: {
      default: {
        light: '#2563EB',
        dark: '#3B82F6',
      },
      hover: {
        light: '#1D4ED8',
        dark: '#60A5FA',
      },
    },
  },
  icon: {
    primary: {
      default: {
        light: '#171717',
        dark: '#FFFFFF',
      },
      disabled: {
        light: '#A3A3A3',
        dark: '#525252',
      },
    },
    secondary: {
      default: {
        light: '#737373',
        dark: '#A3A3A3',
      },
    },
    'on-primary': {
      default: {
        light: '#FFFFFF',
        dark: '#FFFFFF',
      },
    },
  },
  interaction: {
    hover: {
      overlay: {
        light: '#000000',
        dark: '#FFFFFF',
      },
    },
    pressed: {
      overlay: {
        light: '#000000',
        dark: '#FFFFFF',
      },
    },
  },
} as const;
