#!/usr/bin/env tsx
/**
 * Builds design token source files from local JSON token collections.
 * Does NOT require a Figma API token.
 *
 * Reads:  scripts/token-collections/*.json
 * Writes: src/primitives.ts, src/semantic.ts, src/spacing.ts,
 *         src/typography.ts, src/breakpoints.ts, src/css/tokens.css
 *
 * Usage:
 *   npm run build:tokens:local  (from packages/tokens)
 */
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SRC         = path.resolve(__dirname, '../src');
const COLLECTIONS = path.resolve(__dirname, 'token-collections');

// ─── Types ───────────────────────────────────────────────────────────────────

interface ColorValue {
  colorSpace: string;
  components: number[];
  alpha:      number;
  hex:        string;
}

interface Token {
  $type:       'color' | 'number' | 'string' | 'boolean';
  $value:      string | number | boolean | ColorValue;
  $extensions?: {
    'com.figma.codeSyntax'?: { WEB?: string };
    [key: string]: unknown;
  };
}

type TokenTree = { [key: string]: TokenTree | Token };

// ─── Token walker ────────────────────────────────────────────────────────────

function isToken(val: unknown): val is Token {
  return typeof val === 'object' && val !== null && '$type' in val && '$value' in val;
}

interface FlatToken {
  path:   string[];
  type:   Token['$type'];
  value:  string | number | boolean | ColorValue;
  cssVar: string; // e.g. "var(--akds-spacing-scale-01)"
}

function flattenTokens(tree: TokenTree, basePath: string[] = []): FlatToken[] {
  const results: FlatToken[] = [];
  for (const [key, val] of Object.entries(tree)) {
    if (key.startsWith('$')) continue;
    const nodePath = [...basePath, key];
    if (isToken(val)) {
      const cssVar = val.$extensions?.['com.figma.codeSyntax']?.WEB ?? '';
      results.push({ path: nodePath, type: val.$type, value: val.$value, cssVar });
    } else {
      results.push(...flattenTokens(val as TokenTree, nodePath));
    }
  }
  return results;
}

// ─── Value helpers ───────────────────────────────────────────────────────────

function colorToString(value: FlatToken['value']): string {
  if (typeof value === 'object' && value !== null && 'hex' in value) {
    const cv = value as ColorValue;
    if (cv.alpha < 0.9999) {
      const [r, g, b] = cv.components.map(c => Math.round(c * 255));
      // Round alpha to 4 decimal places to avoid floating-point noise (e.g. 0.05999999865889549 → 0.06)
      const a = parseFloat(cv.alpha.toFixed(4));
      return `rgba(${r},${g},${b},${a})`;
    }
    return cv.hex;
  }
  return String(value);
}

function numVal(value: FlatToken['value']): number {
  return typeof value === 'number' ? value : Number(value);
}

function cssVarName(webValue: string): string {
  const m = webValue.match(/^var\((--[^)]+)\)$/);
  return m ? m[1] : webValue;
}

// ─── Nested object builder ───────────────────────────────────────────────────

function buildNested(
  tokens: FlatToken[],
  getValue: (t: FlatToken) => unknown,
): Record<string, unknown> {
  const obj: Record<string, unknown> = {};
  for (const t of tokens) {
    let cur = obj;
    for (let i = 0; i < t.path.length - 1; i++) {
      const k = t.path[i];
      if (typeof cur[k] !== 'object' || cur[k] === null) cur[k] = {};
      cur = cur[k] as Record<string, unknown>;
    }
    cur[t.path[t.path.length - 1]] = getValue(t);
  }
  return obj;
}

// ─── TypeScript serializer ───────────────────────────────────────────────────

function tsLiteral(v: unknown, depth = 0): string {
  if (typeof v === 'string') return `'${v.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
  if (typeof v === 'number') return String(v);
  if (typeof v !== 'object' || v === null) return JSON.stringify(v);

  const entries = Object.entries(v as Record<string, unknown>);
  if (!entries.length) return '{}';

  const pad  = '  '.repeat(depth + 1);
  const cPad = '  '.repeat(depth);
  const lines = entries.map(([k, val]) => {
    const isIdent      = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k);
    const isDecimalInt = /^(0|[1-9]\d*)$/.test(k); // exclude leading-zero numerics (octal)
    const key = isIdent || isDecimalInt ? k : `'${k}'`;
    return `${pad}${key}: ${tsLiteral(val, depth + 1)},`;
  });
  return `{\n${lines.join('\n')}\n${cPad}}`;
}

const AUTO_HEADER =
  `// Auto-generated by scripts/build-from-collections.ts — DO NOT EDIT MANUALLY\n` +
  `// Source of truth: scripts/token-collections/*.json\n` +
  `// Regenerate with: npm run build:tokens:local  (from packages/tokens)\n\n`;

// ─── Collection loader ───────────────────────────────────────────────────────

function load(filename: string, stripPrefix: string[]): FlatToken[] {
  const raw = fs.readFileSync(path.join(COLLECTIONS, filename), 'utf8');
  let tree: unknown = JSON.parse(raw);
  for (const key of stripPrefix) {
    tree = (tree as TokenTree)[key];
    if (tree == null) throw new Error(`Key "${key}" not found in ${filename}`);
  }
  return flattenTokens(tree as TokenTree);
}

// ─── File generators ─────────────────────────────────────────────────────────

function genPrimitives(): string {
  const tokens = load('primitives.json', ['akds', 'primitive', 'color']);
  const obj    = buildNested(tokens, t => colorToString(t.value));
  return (
    AUTO_HEADER +
    `export const primitiveColors = ${tsLiteral(obj)} as const;\n\n` +
    `export type PrimitiveColorScale = keyof typeof primitiveColors;\n`
  );
}

function genSemantic(): string {
  const lightTokens = load('colors-light.json', ['akds', 'color']);
  const darkTokens  = load('colors-dark.json',  ['akds', 'color']);
  const darkMap     = new Map(darkTokens.map(t => [t.path.join('/'), t]));

  const obj = buildNested(lightTokens, lt => {
    const dk    = darkMap.get(lt.path.join('/'));
    const light = colorToString(lt.value);
    const dark  = dk ? colorToString(dk.value) : light;
    return { light, dark };
  });

  return AUTO_HEADER + `export const semanticColors = ${tsLiteral(obj)} as const;\n`;
}

function genSpacing(): string {
  // JSON nests as akds.spacing.*, akds.size.*, akds.radius.*
  // Strip `akds` so the exported object is { spacing: {...}, size: {...}, radius: {...} }
  const tokens = load('spacing.json', ['akds']);
  const obj    = buildNested(tokens, t => numVal(t.value));
  return AUTO_HEADER + `export const spacing = ${tsLiteral(obj)} as const;\n`;
}

// Map JSON font sub-keys → camelCase export keys
const TYPO_KEY: Record<string, string> = {
  family:           'fontFamily',
  size:             'fontSize',
  weight:           'fontWeight',
  'line-height':    'lineHeight',
  'letter-spacing': 'letterSpacing',
};

function genTypography(): string {
  const tokens = load('typography.json', ['akds', 'font']);
  const obj: Record<string, unknown> = {};

  for (const t of tokens) {
    const [rawGroup, ...rest] = t.path;
    const group    = TYPO_KEY[rawGroup] ?? rawGroup;
    const finalPath = [group, ...rest];

    let val: string | number;
    if (rawGroup === 'letter-spacing') {
      // Figma letter-spacing is stored as percent-of-font-size (÷100 = em)
      val = `${numVal(t.value) / 100}em`;
    } else if (t.type === 'string') {
      val = t.value as string;
    } else {
      val = numVal(t.value);
    }

    let cur = obj;
    for (let i = 0; i < finalPath.length - 1; i++) {
      const k = finalPath[i];
      if (typeof cur[k] !== 'object' || cur[k] === null) cur[k] = {};
      cur = cur[k] as Record<string, unknown>;
    }
    cur[finalPath[finalPath.length - 1]] = val;
  }

  return AUTO_HEADER + `export const typography = ${tsLiteral(obj)} as const;\n`;
}

function genBreakpoints(): string {
  const tokens = load('breakpoints.json', ['akds', 'breakpoint']);
  const obj    = buildNested(tokens, t => numVal(t.value));
  return (
    AUTO_HEADER +
    `export const breakpoints = ${tsLiteral(obj)} as const;\n\n` +
    `export type Breakpoint = keyof typeof breakpoints;\n`
  );
}

// ─── CSS generator ───────────────────────────────────────────────────────────

const ELEVATION_CSS_BLOCK = `
  /* ─── Elevation ──────────────────────────────────────────────────────── */
  --akds-elevation-none: none;
  --akds-elevation-xs:   0 1px 2px rgba(0,0,0,0.05);
  --akds-elevation-sm:   0 1px 3px rgba(0,0,0,0.10), 0 1px 2px rgba(0,0,0,0.06);
  --akds-elevation-md:   0 4px 6px rgba(0,0,0,0.07), 0 2px 4px rgba(0,0,0,0.06);
  --akds-elevation-lg:   0 10px 15px rgba(0,0,0,0.10), 0 4px 6px rgba(0,0,0,0.05);
  --akds-elevation-xl:   0 20px 25px rgba(0,0,0,0.10), 0 10px 10px rgba(0,0,0,0.04);
  --akds-elevation-2xl:  0 25px 50px rgba(0,0,0,0.25);`;

// Figma Variables cannot represent CSS shorthand values (outline, box-shadow, etc.)
// so compound focus tokens are hardcoded here. --akds-color-interaction-focus-outline
// is also hardcoded for light mode because Figma only exports it in the dark collection.
const FOCUS_CSS_BLOCK = `
  /* ─── Focus ──────────────────────────────────────────────────────────── */
  --akds-color-interaction-focus-outline: #262626;
  --akds-outline-focus: 2px dotted var(--akds-color-interaction-focus-outline);
  --akds-outline-focus-offset: 1px;`;

function toCssValue(t: FlatToken): string {
  if (t.type === 'color')  return colorToString(t.value);
  if (t.type === 'string') return t.value as string;
  const n   = numVal(t.value);
  const cv  = t.cssVar;
  if (cv.includes('letter-spacing')) return `${n / 100}em`;
  if (cv.includes('line-height'))    return String(n);
  if (cv.includes('font-weight'))    return String(n);
  return `${n}px`;
}

function genCSS(): string {
  const primTokens    = load('primitives.json',   ['akds', 'primitive', 'color']);
  const spacingTokens = load('spacing.json',       ['akds']);
  const typoTokens    = load('typography.json',    ['akds', 'font']);
  const bpTokens      = load('breakpoints.json',   ['akds', 'breakpoint']);
  const lightTokens   = load('colors-light.json',  ['akds', 'color']);
  const darkTokens    = load('colors-dark.json',   ['akds', 'color']);

  const rootLines: string[] = [];

  rootLines.push('  /* ─── Primitives ──────────────────────────────────────────── */');
  for (const t of primTokens) {
    if (!t.cssVar) continue;
    rootLines.push(`  ${cssVarName(t.cssVar)}: ${colorToString(t.value)};`);
  }

  rootLines.push('\n  /* ─── Spacing ──────────────────────────────────────────────── */');
  for (const t of spacingTokens) {
    if (!t.cssVar) continue;
    rootLines.push(`  ${cssVarName(t.cssVar)}: ${numVal(t.value)}px;`);
  }

  rootLines.push('\n  /* ─── Typography ───────────────────────────────────────────── */');
  for (const t of typoTokens) {
    if (!t.cssVar) continue;
    rootLines.push(`  ${cssVarName(t.cssVar)}: ${toCssValue(t)};`);
  }

  rootLines.push('\n  /* ─── Breakpoints ──────────────────────────────────────────── */');
  for (const t of bpTokens) {
    if (!t.cssVar) continue;
    rootLines.push(`  ${cssVarName(t.cssVar)}: ${numVal(t.value)}px;`);
  }

  rootLines.push(ELEVATION_CSS_BLOCK);
  rootLines.push(FOCUS_CSS_BLOCK);

  rootLines.push('\n  /* ─── Semantic colors — Light mode ─────────────────────────── */');
  for (const t of lightTokens) {
    if (!t.cssVar) continue;
    rootLines.push(`  ${cssVarName(t.cssVar)}: ${colorToString(t.value)};`);
  }

  const darkLines: string[] = [];
  for (const t of darkTokens) {
    if (!t.cssVar) continue;
    darkLines.push(`  ${cssVarName(t.cssVar)}: ${colorToString(t.value)};`);
  }

  const hdr =
    `/* Auto-generated by scripts/build-from-collections.ts — DO NOT EDIT MANUALLY */\n` +
    `/* Source: scripts/token-collections/*.json — run \`npm run build:tokens:local\` to regenerate */\n`;

  let css = `${hdr}\n:root {\n${rootLines.join('\n')}\n}\n`;

  if (darkLines.length) {
    css +=
      `\n/* ─── Dark mode — explicit attribute ────────────────────────────── */\n` +
      `[data-theme="dark"] {\n${darkLines.join('\n')}\n}\n` +
      `\n/* ─── Dark mode — OS preference (respects explicit light override) */\n` +
      `@media (prefers-color-scheme: dark) {\n` +
      `  :root:not([data-theme="light"]) {\n` +
      `${darkLines.map(l => '  ' + l).join('\n')}\n` +
      `  }\n}\n`;
  }

  return css;
}

// ─── Main ────────────────────────────────────────────────────────────────────

const FILES = [
  { filePath: path.join(SRC, 'primitives.ts'),  gen: genPrimitives,  label: 'src/primitives.ts'  },
  { filePath: path.join(SRC, 'semantic.ts'),     gen: genSemantic,    label: 'src/semantic.ts'    },
  { filePath: path.join(SRC, 'spacing.ts'),      gen: genSpacing,     label: 'src/spacing.ts'     },
  { filePath: path.join(SRC, 'typography.ts'),   gen: genTypography,  label: 'src/typography.ts'  },
  { filePath: path.join(SRC, 'breakpoints.ts'),  gen: genBreakpoints, label: 'src/breakpoints.ts' },
  { filePath: path.join(SRC, 'css/tokens.css'),  gen: genCSS,         label: 'src/css/tokens.css' },
];

console.log('Building tokens from local JSON collections…');
for (const { filePath, gen, label } of FILES) {
  try {
    fs.writeFileSync(filePath, gen(), 'utf8');
    console.log(`  ✓  ${label}`);
  } catch (err) {
    console.error(`  ✗  ${label}: ${(err as Error).message}`);
    process.exit(1);
  }
}
console.log('\nAll token files updated. Run `npm run build` to rebuild the package.');
